### ISSUE TITLE
Robust_request Function

### ISSUE THREAD

**Issue by vaggarwal4** [iit-cs579/assignments#1]
Hey 
i am having problem in understanding how robust_request function work and how these parameters will work ?

**Comment by ClaytonTurnerOld** [comment]
robust_request is, as said in class today, really a wrapper for the request function for twitter (which in and of itself is a wrapper). 

The in[5] section of the lecture 02 notebook has an example of the regular request function:

# Let's start by querying the search API
request = twitter.request('search/tweets', {'q': 'chicago'}) 

so really what robust request wants you to do is make it so you can make these calls in a wrapper-style format while considering the other parameters such as max_tries.

**Comment by vaggarwal4** [comment]
Fixes#Robust_request Function
