### ISSUE TITLE
How to consider parents 

### ISSUE THREAD

**Issue by Swapnil2095** [iit-cs579/assignments#10]
Hi Professor/TA,

How we should consider parent-child relation in following example.
if we have edges  (node1,node2)  and (node2,node1)

then they are parents to each other as well.
As I can see my output by considering both ways relation-
  [('A', ['B']), ('B', ['D']), ('C', ['B']), ('D', ['B', 'E', 'F', 'G']), ('F', ['D', 'E', 'G']), ('G', ['D', 'F'])]

And your output is
  [('A', ['B']), ('B', ['D']), ('C', ['B']), ('D', ['E']), ('F', ['E']), ('G', ['D', 'F'])]

I am confused whether how you consider here.
Plese, explain what you want here.
Do I need to consider max_depth parameter here as well?

**Comment by aronwc** [comment]
If A is the parent of B, then B cannot be the parent of A.

Recall that this tree we're talking about represents the shortest paths from a root node R to some node A. For B to be the parent of A, that means that some shortest path from R to A passes through the edge (B,A). If this is true, then there can be no shortest path from R to B that passes through edge (A,B).

Thus, in your example output above, if D is a parent of B `[('B', ['D'])]`, then B cannot be a parent of D `[('D', ['B', 'E', 'F', 'G'])]`
