### ISSUE TITLE
a1.py running for too long 

### ISSUE THREAD

**Issue by Swapnil2095** [iit-cs579/assignments#13]
Can anybody will help me to reduced running time.

I have passed my all doc-test but as my program running too long, I am not able to see its output.

**Comment by ClaytonTurnerOld** [comment]
Try going through your main method and seeing where the prints are coming out (maybe add some extra print statements).

If there is a part where it's taking exceedingly long, then check out which function it is by looking at what has printed and what hasn't.

Then try to add some prints inside that function - you'll find a bottleneck and then you can try and tinker with it.

**Comment by vmanikes** [comment]
It might have gone into a infinite loop. Please check that

**Comment by Swapnil2095** [comment]
No, it is not going into infinite loop.
I wrote extra doc-tests. Those also giving the right results.

**Comment by Swapnil2095** [comment]
[log_wo_set_max_score.txt](https://github.com/iit-cs579/assignments/files/504456/log_wo_set_max_score.txt)

See this log file.

If my logic was not right , So how I can get correct partition .

See the result without following function calling --
    print('norm_cut scores by max_depth:')
    print(score_max_depths(subgraph, range(1,5)))

I think, problem id different here. I sent a mail containing my a1.py file.
So please check once and let me know.

**Comment by gautammishra** [comment]
Same here. My program does pass all the doctests but takes 53 minutes to do so.

**Comment by ClaytonTurnerOld** [comment]
Again, I'm going to re-suggest my print method from earlier in this thread in order to figure out where your program is taking up all this time. 

Find whichever function(s) are doing this, then try to optimize it.

**Comment by dandandanliu915** [comment]
My codes was running very slowly too. But I figured out it is the problem that my bfs method is not the optimal realization of the algorithm. Suggest you can check your bfs first.
