### ISSUE TITLE
Scope/Code Indentation problems :|

### ISSUE THREAD

**Issue by kartikaygautam** [iit-cs579/assignments#14]
Somehow indenting the code is not keeping it in scope.

Details : -

Have an if statement block where, if the test fails, roughly a half of the code, the first part, doesn't run but the latter half does :P

**Comment by ClaytonTurnerOld** [comment]
Maybe you're mixing spaces and tabs and it's not agreeing with everything. 

Try using the reindent.py module perhaps: http://stackoverflow.com/a/1024489/4280550
