### ISSUE TITLE
How to handle case for a graph with max_depth = 1

### ISSUE THREAD

**Issue by Swapnil2095** [iit-cs579/assignments#16]
in partition_girvan_newman function , when I m calling to approximate_betweenness function 

For max_depth == 1 , it gives me empty edges to remove.
Please suggest how to handle this condition.

   G.remove_edge(*edge_to_remove)
TypeError: remove_edge() missing 2 required positional arguments: 'u' and 'v'

**Comment by dandandanliu915** [comment]
I think you just need to remove the edges with betweenness from the highest until you get two separated components. For case max_depth = 1, betweenness equals to 1 for all edges. So you just need to remove them one by one according to the alphabetical order of the edges, until two components exist. 
Just some thoughts.
