### ISSUE TITLE
Output Issue

### ISSUE THREAD

**Issue by pratik27shah** [iit-cs579/assignments#18]
Hi,

My output comes as per the log.txt but the order 'cluster 2 nodes:' is not same as the log file.So is this an acceptable case.The order of output for 'cluster 2 nodes:' changes,not the contents in it they are all the same for every run.

**Comment by ClaytonTurnerOld** [comment]
This is fine. See: https://github.com/iit-cs579/main/issues/222 and https://github.com/iit-cs579/main/issues/205
