### ISSUE TITLE
Regarding next assignment (A2) and topics covered by midterm

### ISSUE THREAD

**Issue by gershwinlover** [iit-cs579/assignments#20]
Hello Dr. Aron,

How are you! I hope you are enjoying this week. I just have a quick question as below.

Would you like to disclose some information about the next upcoming assignment, A2? I'm wondering what topics will be covered by this assignment. As you know, A1 only covers up to Link prediction. But our midterm also includes Cascading and Sentiment Analysis. If A2 is about these topics, could you please post A2 today or tomorrow? 

By the way, will the solution for A1 (or a sample code) be published after its due? We talked about the solution to A0 during one of our lecture; but we will not have lecture next week...

Warmest Regards,
Zhidu

**Comment by aronwc** [comment]
I'm working on A2 now.
