### ISSUE TITLE
Question about Assignment 2 eval_all_combinations()

### ISSUE THREAD

**Issue by gershwinlover** [iit-cs579/assignments#21]
Hello Dr. Aron,

So sorry to bother during the weekend. I have a quick question about A2, function eval_all_combinations(). In the description, it says if feature_fns = [token_features, token_pair_features, lexicon_features], then we will consider all 4 combinations of features.

Assuming we have a set [A,B,C], we can have 8 combinations: (empty),A, B, C, AB, AC, BC, ABC; In the log:
    features=token_pair_features lexicon_features: 0.75125
    features=token_features token_pair_features lexicon_features: 0.74583
    features=token_features token_pair_features: 0.73542
    features=token_pair_features: 0.72875
it is something equivalent to having BC, ABC, AB and B. Why is this the case?

Regards,
Zhidu

**Comment by aronwc** [comment]
You're right it is more combinations (no need to consider the empty set).

**Comment by gershwinlover** [comment]
thanks a tons!

**Comment by gershwinlover** [comment]
I think I misunderstood the log.txt file. There are 7 combinations in that output. So sorry about this confusion.
