### ISSUE TITLE
Assignment 2 different worst result

### ISSUE THREAD

**Issue by gershwinlover** [iit-cs579/assignments#25]
Now my output is exactly same as the Log.txt file except the following:

worst cross-validation result:
{'min_freq': 10, 'accuracy': 0.64749999999999996, 'punct': True, 'features': (<function lexicon_features at 0x10eb58e18>,)}

In the Log.txt, min_freq is 2 (everything else is the same, even accuracy). What a coincidence!

I'm just wondering why this is the case...Anyone has any idea?

**Comment by aronwc** [comment]
It looks like you're not using any feature functions? Each combination should use at least one feature.

**Comment by gershwinlover** [comment]
Oh! Yes..you are right. Thanks!

I found the bug in the function where I append the dict for each combinations of settings...

**Comment by gershwinlover** [comment]
I think that's because github deleted that...from this text editor...You know, they are trying to prevent malicious behavior.

**Comment by gershwinlover** [comment]
![screen shot 2016-10-10 at 12 10 44 pm](https://cloud.githubusercontent.com/assets/17130824/19244613/bf4645ec-8ee2-11e6-8b44-517dd3c15ea7.png)

**Comment by gershwinlover** [comment]
![screen shot 2016-10-10 at 12 17 25 pm](https://cloud.githubusercontent.com/assets/17130824/19244773/89afed56-8ee3-11e6-806e-2df4f3bf4cbd.png)
Okay, now when looking at more results, I realize that the worst 3 has the same accuracy, because they all use lexicon only. Even though the tokens will be different when using different "min_freq", the neg_words set and pos_words set are too small! They become the bottleneck for this method. That's why the worst 3 methods have the same accuracy.

**Comment by gershwinlover** [comment]
Late question...is my output okay in this case or it need to be sorted in descending order by min_freq? I think the higher min_freq, the worse accuracy. (This may not be true in case of overfitting; but generally speaking, if I choose a very very high min_freq, I will get very few tokens selected and then no accuracy) So I think higher min_freq gives worse result. The following picture proves that:
![screen shot 2016-10-10 at 12 29 53 pm](https://cloud.githubusercontent.com/assets/17130824/19245165/4b5bdc3e-8ee5-11e6-862d-1d890a28519d.png)
You can see that the first setting with min_freq = 2 has an accuracy of 0.76500000000000001; whereas the second setting is the same as the first one except min_freq = 5 with accuracy = 0.7649999999999999
