### ISSUE TITLE
def count_friends(user)

### ISSUE THREAD

**Issue by vaggarwal4** [iit-cs579/assignments#3]
Hey!!
Can anyone explain what does this function do. I'm not able to understand it and also the example is not clear to me.

**Comment by ClaytonTurnerOld** [comment]
In this example, friend '2' is followed by three different users.
    >>> c = count_friends([{'friends': [1,2]}, {'friends': [2,3]}, {'friends': [2,3]}])
    >>> c.most_common()
    [(2, 3), (3, 2), (1, 1)]

The friends in this example are the numbers 1, 2, and 3. You really just want to count how many times these things are coming up but while using the Counter object. 2 showed up 3 times in the example, 3 showed up 1 time, and 1 showed up 1 time. So "c.most_common()" is printing out a tuple showing that.

If it makes it easier, then here's the same example but without confusing-ness:

In this example, friend 'b' is followed by three different users.
    >>> c = count_friends([{'friends': [a,b]}, {'friends': [b,c]}, {'friends': [b,c]}])
    >>> c.most_common()
    [(b, 3), (c, 2), (a, 1)]

**Comment by vaggarwal4** [comment]
thnx clayton
