### ISSUE TITLE
Not able to return objects from get_user function

### ISSUE THREAD

**Issue by Swapnil2095** [iit-cs579/assignments#4]
I am not able to return any user from get_users(twitter, screen_names) function

```
user = twitter.request('users/search', {'q': screen_names[2]}) 

print('Code returned =', user.status_code)

if user.status_code==200 :
    print('Call SuccessFul')
    for item in user.get_iterator():
        print('id=%d screen_name=%s, name=%s, location=%s' % (item['id'],item['screen_name'],item['name'], item['location']))

else:
    print('Call failed')
```

Output->

Traceback (most recent call last):
  File "C:\Users\Swapnil\workspace\Assignment1\a0.py", line 410, in <module>
    main()
  File "C:\Users\Swapnil\workspace\Assignment1\a0.py", line 387, in main
    users = sorted(get_users(twitter, screen_names), key=lambda x: x['screen_name'])
TypeError: 'NoneType' object is not iterable

**Comment by ClaytonTurnerOld** [comment]
For starters, you should be using your robust_request function instead of enacting twitter.request(), but that really shouldn't be causing errors

Try using the "users/lookup" resource instead of "users/search"
