### ISSUE TITLE
get_friends() doc test

### ISSUE THREAD

**Issue by vaggarwal4** [iit-cs579/assignments#5]
Sir
When i am running the doc test for get_friends(twitter, 'aronwc')[:5] getting the list of friends but the order is not same as [695023, 1697081, 8381682, 10204352, 11669522] the order is [90155533, 216939636, 264501255, 10204352, 142594034] but the whole list has all the friends id including the one in the doctest sample
and it is also working fine in case of presidential candidates

**Comment by ClaytonTurnerOld** [comment]
The directions say you're supposed to sort the list for the return statement

**Comment by vaggarwal4** [comment]
thnx
