### ISSUE TITLE
File upload problem

### ISSUE THREAD

**Issue by vaggarwal4** [iit-cs579/assignments#6]
hey 
I have uploaded my assignment file in the private repository in folder ao
the files that i have uploaded are
AO.ipynb and twitter.cgf
but when i execute my code(its working correct) but i cant see my network .npg file in the repository 
can anyone tell me are they facing same problem or the link where the network.png get generated

**Comment by AndrewLu1992** [comment]
First, do not change any filenames. a0.py and ShortAnswer.txt in your private repository. 
I have seen your repo it seems that you implement in Ipython Notebook, which is Okay but you still need to upload a0.py which is not a .ipynb file. 
You are responsible for resolving the graph drawing and writing part.
