### ISSUE TITLE
[HW1] Do we need to realize BFS function without calling other library

### ISSUE THREAD

**Issue by sure00** [iit-cs579/assignments#7]
Hi Professor
Can we call the function _single_source_shortest_path_basic(graph, s) to find the shortest path between root and other nodes? Or we must realize BFS function without calling other libraries such as calling _single_source_shortest_path_basic function?

**Comment by aronwc** [comment]
No, you should not use networkx's shortest path implementations. 
The only thing you should need from networkx is graph.neighbors(x) to get the neighbors of x.
As I also mentioned in the comments, defaultdict and dequeue may also be used.
