### ISSUE TITLE
Do you want to use bfs algo to fill node2num_paths dict as well

### ISSUE THREAD

**Issue by Swapnil2095** [iit-cs579/assignments#9]
in function  bfs(graph, root, max_depth) - Do you want to use bfs algo to fill node2num_paths dict as well

I have filled node2distances dict. But not getting how I can manage to find multiple short_paths from bfs algo.
or 

We can use _single_source_shortest_path_basic(graph, s) to do our purpose.

**Comment by ClaytonTurnerOld** [comment]
Yes, node2num_paths needs to be filled in during the process of your bfs algorithm (it's one of the return values)

This needs to be done from scratch so you cannot use single_source_shortest...
